apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/ibm-eventprocessing.openshift-operators: ''
  name: ibm-eventprocessing
  namespace: openshift-operators
spec:
  channel: v1.1
  installPlanApproval: Automatic
  name: ibm-eventprocessing
  source: ibm-eventprocessing-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: ibm-eventprocessing.v1.1.9