apiVersion: operator.ibm.com/v1alpha1
kind: CertManager
metadata:
  labels:
    app.kubernetes.io/instance: ibm-cert-manager-operator
    app.kubernetes.io/managed-by: ibm-cert-manager-operator
    app.kubernetes.io/name: cert-manager
  name: ibm-certmanager-svil
spec:
  license:
    accept: true
  certManagerCAInjector:
    resources:
      limits:
        cpu: 100m
        memory: 520Mi
      requests:
        cpu: 20m
        memory: 410Mi
  certManagerController:
    resources:
      limits:
        cpu: 80m
        memory: 530Mi
      requests:
        cpu: 20m
        memory: 230Mi
  certManagerWebhook:
    resources:
      limits:
        cpu: 60m
        memory: 100Mi
      requests:
        cpu: 30m
        memory: 40Mi
  disableHostNetwork: true
  enableCertRefresh: true
  enableWebhook: true
  imageRegistry: icr.io/cpopen/cpfs
  version: 3.18.0

