apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cert-manager-4.0.0
  publisher: IBM
  image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:9ecbd78444208da0e2981b7a9060d2df960e09b59ac9990a959df069864085c2
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 30m0s
