apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-event-processing-operator
spec:
  project: proj-eventautomation
  source:
    path: ibm-event-processing/operator/
    repoURL: 'https://github.com/fdaluisio/ibm-operator/'
    targetRevision: HEAD
  destination:
    namespace: openshift-operators
    server: 'https://kubernetes.default.svc'